Attribute VB_Name = "A_DefaultConfig"
Option Explicit
Option Private Module

'NO NOT REMOVE THIS TAG
Sub DefaultConfig()
    With gVim.Config
        .VimToggleKey = "<C-m>"
    End With

    With gVim.KeyMap
        ' === Pictures ===
        .Map "nmap xp CopyPasteAsPictureToPPT"

        ' === Charts ===
        .Map "nmap fg FormatChart_FG"
        .Map "nmap gd MDL_SelectDataLabels"
        .Map "nmap gh MDL_Left"
        .Map "nmap gl MDL_Right"
        .Map "nmap gk MDL_Up"
        .Map "nmap gj MDL_Down"
        .Map "nmap gH MDL_SingleLeft"
        .Map "nmap gL MDL_SingleRight"
        .Map "nmap gK MDL_SingleUp"
        .Map "nmap gJ MDL_SingleDown"
        .Map "nmap gc SelectNearestChart"

        ' === Borders ===
        .Map "nmap bsh CycleBorderLeft"
        .Map "nmap bsj CycleBorderBottom"
        .Map "nmap bsk CycleBorderTop"
        .Map "nmap bsl CycleBorderRight"
        .Map "nmap bb ToggleBorderAll 1 2"
        .Map "nmap ba ToggleBorderAround 1 2"
        .Map "nmap bh ToggleBorderLeft 1 2"
        .Map "nmap bj ToggleBorderBottom 1 2"
        .Map "nmap bk ToggleBorderTop 1 2"
        .Map "nmap bl ToggleBorderRight 1 2"
        .Map "nmap bia ToggleBorderInner 1 2"
        .Map "nmap bis ToggleBorderInnerHorizontal 1 2"
        .Map "nmap biv ToggleBorderInnerVertical 1 2"
        .Map "nmap b/ ToggleBorderDiagonalUp 1 2"
        .Map "nmap b<bslash> ToggleBorderDiagonalDown 1 2"
        .Map "nmap bB ToggleBorderAll 1 4"
        .Map "nmap bA ToggleBorderAround 1 4"
        .Map "nmap bH ToggleBorderLeft 1 4"
        .Map "nmap bJ ToggleBorderBottom 1 4"
        .Map "nmap bK ToggleBorderTop 1 4"
        .Map "nmap bL ToggleBorderRight 1 4"
        .Map "nmap Bia ToggleBorderInner 1 4"
        .Map "nmap Bis ToggleBorderInnerHorizontal 1 4"
        .Map "nmap Biv ToggleBorderInnerVertical 1 4"
        .Map "nmap B/ ToggleBorderDiagonalUp 1 4"
        .Map "nmap B<bslash> ToggleBorderDiagonalDown 1 4"
        .Map "nmap bob ToggleBorderAll 1 1"
        .Map "nmap boa ToggleBorderAround 1 1"
        .Map "nmap boh ToggleBorderLeft 1 1"
        .Map "nmap boj ToggleBorderBottom 1 1"
        .Map "nmap bok ToggleBorderTop 1 1"
        .Map "nmap bol ToggleBorderRight 1 1"
        .Map "nmap boia ToggleBorderInner 1 1"
        .Map "nmap bois ToggleBorderInnerHorizontal 1 1"
        .Map "nmap boiv ToggleBorderInnerVertical 1 1"
        .Map "nmap bo/ ToggleBorderDiagonalUp 1 1"
        .Map "nmap bo<bslash> ToggleBorderDiagonalDown 1 1"
        .Map "nmap bmb ToggleBorderAll 1 -4138"
        .Map "nmap bma ToggleBorderAround 1 -4138"
        .Map "nmap bmh ToggleBorderLeft 1 -4138"
        .Map "nmap bmj ToggleBorderBottom 1 -4138"
        .Map "nmap bmk ToggleBorderTop 1 -4138"
        .Map "nmap bml ToggleBorderRight 1 -4138"
        .Map "nmap bmia ToggleBorderInner 1 -4138"
        .Map "nmap bmis ToggleBorderInnerHorizontal 1 -4138"
        .Map "nmap bmiv ToggleBorderInnerVertical 1 -4138"
        .Map "nmap bm/ ToggleBorderDiagonalUp 1 -4138"
        .Map "nmap bm<bslash> ToggleBorderDiagonalDown 1 -4138"
        .Map "nmap btb ToggleBorderAll -4119 4"
        .Map "nmap bta ToggleBorderAround -4119 4"
        .Map "nmap bth ToggleBorderLeft -4119 4"
        .Map "nmap btj ToggleBorderBottom -4119 4"
        .Map "nmap btk ToggleBorderTop -4119 4"
        .Map "nmap btl ToggleBorderRight -4119 4"
        .Map "nmap btia ToggleBorderInner -4119 4"
        .Map "nmap btis ToggleBorderInnerHorizontal -4119 4"
        .Map "nmap btiv ToggleBorderInnerVertical -4119 4"
        .Map "nmap bt/ ToggleBorderDiagonalUp -4119 4"
        .Map "nmap bt<bslash> ToggleBorderDiagonalDown -4119 4"
        .Map "nmap bn DeleteBorderAll"
        .Map "nmap bda DeleteBorderAround"
        .Map "nmap bdh DeleteBorderLeft"
        .Map "nmap bdj DeleteBorderBottom"
        .Map "nmap bdk DeleteBorderTop"
        .Map "nmap bdl DeleteBorderRight"
        .Map "nmap bdia DeleteBorderInner"
        .Map "nmap bdis DeleteBorderInnerHorizontal"
        .Map "nmap bdiv DeleteBorderInnerVertical"
        .Map "nmap bd/ DeleteBorderDiagonalUp"
        .Map "nmap bd<bslash> DeleteBorderDiagonalDown"
        .Map "nmap bcc SetBorderColorAll"
        .Map "nmap bca SetBorderColorAround"
        .Map "nmap bch SetBorderColorLeft"
        .Map "nmap bcj SetBorderColorBottom"
        .Map "nmap bck SetBorderColorTop"
        .Map "nmap bcl SetBorderColorRight"
        .Map "nmap bcia SetBorderColorInner"
        .Map "nmap bcis SetBorderColorInnerHorizontal"
        .Map "nmap bciv SetBorderColorInnerVertical"
        .Map "nmap bc/ SetBorderColorDiagonalUp"
        .Map "nmap bc<bslash> SetBorderColorDiagonalDown"
        .Map "nmap bc ChangeShapeBorderColor"

        ' === Fonts & Format ===
        .Map "nmap fG SetFontGaramond"
        .Map "nmap fr SmartFormatRight"
        .Map "nmap fx OutlineSelectionHighlight"
        .Map "nmap <C-S-z> CycleFontColor"
        .Map "nmap - DecreaseFontSize"
        .Map "nmap + IncreaseFontSize"
        .Map "nmap fn ChangeFontName"
        .Map "nmap fs ChangeFontSize"
        .Map "nmap fb ToggleBold"
        .Map "nmap fi ToggleItalic"
        .Map "nmap fu ToggleUnderline"
        .Map "nmap ft ChangeFormat"
        .Map "nmap ff ShowFontDialog"
        .Map "nmap Fc SmartFontColor"
        .Map "nmap v ColorSelectionYellow"

        ' === Numbers ===
        .Map "nmap <C-,> IncreaseDecimalPlaces"
        .Map "nmap <C-.> DecreaseDecimalPlaces"
        .Map "nmap ( IncreaseDecimal"
        .Map "nmap ) DecreaseDecimal"
        .Map "nmap <C-S-A> AddNumber"
        .Map "nmap <C-S-X> SubtractNumber"
        .Map "nmap g<C-A> VisualAddNumber"
        .Map "nmap g<C-X> VisualSubtractNumber"
        '.Map "nmap =s AutoSum"
        '.Map "nmap =a AutoAverage"
        '.Map "nmap =c AutoCount"
        '.Map "nmap =m AutoMax"
        '.Map "nmap =i AutoMin"

        ' === Editing ===
        .Map "nmap wf ClearUnnecessaryFormatting"
        .Map "nmap = """
        .Map "nmap dd DeleteLikeExcel"
        .Map "nunmap <Del>"
        .Map "nmap df ClearFormatting"
        .Map "nmap <C-S-d> SmartFillDown"
        .Map "nmap <C-S-r> SmartFillRight"
        .Map "nmap <C-S-w> WrapFormulaWithCircCheck"
        .Map "nmap o InsertCellsDown"
        .Map "nmap O InsertCellsUp"
        .Map "nmap t InsertCellsRight"
        .Map "nmap T InsertCellsLeft"
        .Map "nmap zw ToggleWrapText"
        .Map "nmap & ToggleMergeCells"
        .Map "nmap Ff ApplyFlashFill"
        .Map "nmap Fa ApplyAutoFill"
        .Map "nmap rd DeleteRows"
        .Map "nmap cd DeleteColumns"
        .Map "nmap X DeleteValue"
        .Map "nmap D DeleteValue"
        .Map "nmap dga DeleteUsedRange"
        .Map "nmap dgA DeleteAllCells"
        .Map "nmap dr DeleteRows"
        .Map "nmap dc DeleteColumns"
        .Map "nmap dgg DeleteRows 5"
        .Map "nmap dgG DeleteRows 1"
        .Map "nmap dG DeleteRows 2"
        .Map "nmap d{ DeleteRows 3"
        .Map "nmap d} DeleteRows 4"
        .Map "nmap dar DeleteRows 6"
        .Map "nmap d0 DeleteColumns 5"
        .Map "nmap d^ DeleteColumns 1"
        .Map "nmap d$ DeleteColumns 2"
        .Map "nmap dg^ DeleteColumns 3"
        .Map "nmap dg$ DeleteColumns 4"
        .Map "nmap dac DeleteColumns 6"
        .Map "nmap dh DeleteToLeft"
        .Map "nmap dj DeleteToUp"
        .Map "nmap dk DeleteToUp"
        .Map "nmap dl DeleteToLeft"
        .Map "nmap fc SmartFillColor"
        .Map "nmap Ce DeleteCellComment"
        .Map "nmap Cx DeleteCellComment"
        .Map "nmap Cd DeleteCellComment"
        .Map "nmap CE DeleteCellCommentAll"
        .Map "nmap CD DeleteCellCommentAll"
        .Map "nmap wd DeleteSheet"

        ' === Movement & Selection ===
        .Map "nmap gR ReverseSelectionOrder"
        .Map "nmap h MoveLeftSmart"
        .Map "nmap j MoveDownSmart"
        .Map "nmap k MoveUpSmart"
        .Map "nmap l MoveRightSmart"
        .Map "nmap H MoveLeftWithShift"
        .Map "nmap J MoveDownWithShift"
        .Map "nmap K MoveUpWithShift"
        .Map "nmap L MoveRightWithShift"
        .Map "nmap <C-h> MoveLeft"
        .Map "nmap <C-j> MoveDown"
        .Map "nmap <C-k> MoveUp"
        .Map "nmap <C-l> MoveRight"
        .Map "nmap <C-S-H> MoveLeft"
        .Map "nmap <C-S-J> MoveDown"
        .Map "nmap <C-S-K> MoveUp"
        .Map "nmap <C-S-L> MoveRight"
        .Map "nmap gg MoveToFirstRow"
        .Map "nmap gG MoveToTopRow"
        .Map "nmap G MoveToLastRow"
        .Map "nmap <bar> MoveToNthColumn"
        .Map "nmap ^ MoveToLeftEnd"
        .Map "nmap $ MoveToRightEnd"
        .Map "nmap g0 MoveToA1"
        .Map "nmap { MoveToTopOfCurrentRegion"
        .Map "nmap } MoveToBottomOfCurrentRegion"
        .Map "nmap ga SelectUsedRange"
        .Map "nmap gA SelectAllCells"
        .Map "nmap wh MoveSheetBack"
        .Map "nmap wl MoveSheetForward"
        .Map "nmap <cmd>unique RemoveDuplicates"

        ' === Navigation & References ===
        .Map "nmap <Space> SubstituteFollowLangMode"
        .Map "nmap <C-F2> LockCellReference"
        .Map "nmap <C-[> FormulaNavigatorHotkeyFallback"
        .Map "nmap : EnterCmdlineMode"
        .Map "nmap a AppendFollowLangMode"
        .Map "nmap A AppendNotFollowLangMode"
        .Map "nmap i InsertFollowLangMode"
        .Map "nmap I InsertNotFollowLangMode"
        '.Map "nmap s SubstituteFollowLangMode"
        .Map "nmap S SubstituteNotFollowLangMode"
        .Map "nmap / ShowFindFollowLang"
        .Map "nmap ? ShowFindNotFollowLang"

        ' === Modes & Toggles ===
        .Map "nmap <C-S-A-.> TogglePlainKeyMappings"
        .Map "nmap sl ToggleScrollLockMode"
        .Map "nmap <C-F11> ToggleScrollLockMode"
        .Map "nmap <cmd>plainkeys TogglePlainKeyMappings"
        .Map "nmap <cmd>override OverrideShortcuts"
        .Map "nmap <cmd>fast ToggleMacroSafeMode"
        .Map "nmap <cmd>info ShowCommandInfo"
        .Map "nmap <C-p> ToggleLang"
        .Map "nmap <cmd>debug ToggleDebugMode"
        .Map "nmap f- ToggleStrikethrough"
        .Map "nmap Ca ToggleCellComment"
        .Map "nmap CA ToggleCellCommentAll"
        .Map "nmap ~ ToggleReadOnly"
        .Map "nmap zf ToggleFreezePanes"
        '.Map "nmap =v ToggleFormulaBar"
        .Map "nmap gb ToggleGridlines"
        .Map "nmap gh ToggleHeadings"

        ' === Links ===
        .Map "nmap gi InsertHyperlinkDialog"
        .Map "nmap gf FollowHyperlinkOfActiveCell"

        ' === Other ===
        .Map "nmap <C-S-x> CycleFillColor"
        .Map "nmap <C-S-a> CycleNumberFormat"
        .Map "nmap <C-S-b> BinaryCycle"
        .Map "nmap <C-S-9> YearDisplayCycle"
        .Map "nmap <C-S-n> NumberNarrativeCycle"
        .Map "nmap <C-S-p> PercentCycle"
        .Map "nmap <C-S-A-j> CycleRowHeight"
        .Map "nmap <C-S-A-l> CycleColumnWidth"
        .Map "nmap ck CenterAcrossSelection"
        .Map "nmap <C-S-e> WrapInIFERROR"
        .Map "nmap <C-S-M> CycleFormatting"
        .Map "nmap <C-S-c> CurrencyCycle"
        .Map "nmap <C-S-i> CycleChartType"
        .Map "nmap <C-_> FlipSign"
        .Map "nmap <cmd>reload ReloadVim"
        .Map "nmap <cmd>version ShowVersion"
        .Map "nmap > IncrementText"
        .Map "nmap <lt> DecrementText"
        .Map "nmap f, ApplyCommaStyle"
        '.Map "nmap <S-Space> ExceptSelectCells"
        .Map "nmap <S-BS> ClearSelectCells"
        '.Map "nmap == InsertFunction"
        .Map "nmap r- NarrowRowsHeight"
        .Map "nmap r+ WideRowsHeight"
        .Map "nmap rr SelectRows"
        .Map "nmap ra AppendRows"
        .Map "nmap ri InsertRows"
        .Map "nmap ry YankRows"
        .Map "nmap rx CutRows"
        .Map "nmap rh HideRows"
        .Map "nmap rH UnhideRows"
        .Map "nmap rg GroupRows"
        .Map "nmap ru UngroupRows"
        .Map "nmap rf FoldRowsGroup"
        .Map "nmap rs SpreadRowsGroup"
        .Map "nmap rj AdjustRowsHeight"
        .Map "nmap rw SetRowsHeight"
        .Map "nmap rl ApplyRowsLock"
        .Map "nmap rL ClearRowsLock"
        .Map "nmap c- NarrowColumnsWidth"
        .Map "nmap c+ WideColumnsWidth"
        .Map "nmap cc SelectColumns"
        .Map "nmap ca AppendColumns"
        .Map "nmap ci InsertColumns"
        .Map "nmap cy YankColumns"
        .Map "nmap cx CutColumns"
        .Map "nmap ch HideColumns"
        .Map "nmap cH UnhideColumns"
        .Map "nmap cg GroupColumns"
        .Map "nmap cu UngroupColumns"
        .Map "nmap cf FoldColumnsGroup"
        .Map "nmap cs SpreadColumnsGroup"
        .Map "nmap cj AdjustColumnsWidth"
        .Map "nmap cw SetColumnsWidth"
        .Map "nmap cl ApplyColumnsLock"
        .Map "nmap cL ClearColumnsLock"
        .Map "nmap yy YankCell"
        .Map "nmap yga YankUsedRange"
        .Map "nmap ygA YankAllCells"
        .Map "nmap yr YankRows"
        .Map "nmap yc YankColumns"
        .Map "nmap ygg YankRows 5"
        .Map "nmap ygG YankRows 1"
        .Map "nmap yG YankRows 2"
        .Map "nmap y{ YankRows 3"
        .Map "nmap y} YankRows 4"
        .Map "nmap yar YankRows 6"
        .Map "nmap y0 YankColumns 5"
        .Map "nmap y^ YankColumns 1"
        .Map "nmap y$ YankColumns 2"
        .Map "nmap yg^ YankColumns 3"
        .Map "nmap yg$ YankColumns 4"
        .Map "nmap yac YankColumns 6"
        .Map "nmap yh YankFromLeftCell"
        .Map "nmap yj YankFromDownCell"
        .Map "nmap yk YankFromUpCell"
        .Map "nmap yl YankFromRightCell"
        .Map "nmap Y YankAsPlaintext"
        .Map "nmap xx CutCell"
        .Map "nmap xga CutUsedRange"
        .Map "nmap xgA CutAllCells"
        .Map "nmap xr CutRows"
        .Map "nmap xc CutColumns"
        .Map "nmap xgg CutRows 5"
        .Map "nmap xgG CutRows 1"
        .Map "nmap xG CutRows 2"
        .Map "nmap x{ CutRows 3"
        .Map "nmap x} CutRows 4"
        .Map "nmap xar CutRows 6"
        .Map "nmap x0 CutColumns 5"
        .Map "nmap x^ CutColumns 1"
        .Map "nmap x$ CutColumns 2"
        .Map "nmap xg^ CutColumns 3"
        .Map "nmap xg$ CutColumns 4"
        .Map "nmap xac CutColumns 6"
        .Map "nmap p PasteSmart 1"
        .Map "nmap P PasteSmart 2"
        .Map "nmap gp PasteSpecial"
        .Map "nmap U PasteValue"
        .Map "nmap <C-S-q> PasteExact"
        .Map "nmap <cmd>cons PasteCondensed"
        .Map "nmap <cmd>num CmdInsertNumbers"
        .Map "nmap <cmd>econs Econs_Output_PPT_V2"
        .Map "nmap <cmd>bo FormatOverviewGraph"
        .Map "nmap <cmd>size ResizeSelectionToWidthPrompt"
        .Map "nmap <cmd>reset ResetWorkbookView"
        .Map "nmap fh AlignLeft"
        .Map "nmap fj AlignBottom"
        .Map "nmap fk AlignTop"
        .Map "nmap fl AlignRight"
        .Map "nmap fo AlignCenter"
        .Map "nmap fm AlignMiddle"
        .Map "nmap Ci EditCellComment"
        .Map "nmap Cc EditCellComment"
        .Map "nmap Cr ShowCellComment"
        .Map "nmap Cm HideCellComment"
        .Map "nmap CR ShowCellCommentAll"
        .Map "nmap CM HideCellCommentAll"
        .Map "nmap CH HideCellCommentIndicator"
        .Map "nmap Cn NextComment"
        .Map "nmap Cp PrevComment"

        ' === Research Links (command mode) ===
        .Map "nmap <cmd>edgar LaunchResearchLink edgar"
        .Map "nmap <cmd>alpha LaunchResearchLink alpha"
        .Map "nmap <cmd>fred LaunchResearchLink fred"
        .Map "nmap <cmd>bam LaunchResearchLink bam"
        .Map "nmap <cmd>cap LaunchResearchLink cap"
        .Map "nmap n NextFoundCell"
        .Map "nmap N PreviousFoundCell"
        .Map "nmap R ShowReplaceWindow"
        .Map "nmap * FindActiveValueNext"
        .Map "nmap # FindActiveValuePrev"
        .Map "nmap ]c NextSpecialCells -4144"
        .Map "nmap [c PrevSpecialCells -4144"
        .Map "nmap ]o NextSpecialCells 2"
        .Map "nmap [o PrevSpecialCells 2"
        .Map "nmap ]f NextSpecialCells -4123"
        .Map "nmap [f PrevSpecialCells -4123"
        .Map "nmap ]k NextSpecialCells 4"
        .Map "nmap [k PrevSpecialCells 4"
        .Map "nmap ]t NextSpecialCells -4173"
        .Map "nmap [t PrevSpecialCells -4173"
        .Map "nmap ]v NextSpecialCells -4175"
        .Map "nmap [v PrevSpecialCells -4175"
        .Map "nmap ]s NextShape"
        .Map "nmap [s PrevShape"
        .Map "nmap <C-u> ScrollUpHalf"
        .Map "nmap <C-d> ScrollDownHalf"
        .Map "nmap <C-b> ScrollUp"
        .Map "nmap <C-y> RedoExecute"
        .Map "nmap <C-e> ScrollDown1Row"
        .Map "nmap , ScrollLeftHalf"
        .Map "nmap ; ScrollRightHalf"
        .Map "nmap zh ScrollLeft1Column"
        .Map "nmap zl ScrollRight1Column"
        .Map "nmap zH ScrollLeft"
        .Map "nmap zL ScrollRight"
        .Map "nmap zt ScrollCurrentTop"
        .Map "nmap zz ScrollCurrentMiddle"
        .Map "nmap zb ScrollCurrentBottom"
        .Map "nmap zs ScrollCurrentLeft"
        .Map "nmap zm ScrollCurrentCenter"
        .Map "nmap ze ScrollCurrentRight"
        .Map "nmap e NextSheet"
        .Map "nmap E PreviousSheet"
        .Map "nmap ww ShowSheetPicker"
        .Map "nmap ws ShowSheetPicker"
        .Map "nmap wn NextSheet"
        .Map "nmap wp PreviousSheet"
        .Map "nmap wr RenameSheet"
        .Map "nmap wi InsertWorksheet"
        .Map "nmap wa AppendWorksheet"
        .Map "nmap w0 ActivateLastSheet"
        .Map "nmap w$ ActivateLastSheet"
        .Map "nmap wc ChangeSheetTabColor"
        .Map "nmap wy CloneSheet"
        .Map "nmap we ExportSheet"
        .Map "nmap w ActivateSheet"
        .Map "nmap <cmd>preview PrintPreviewOfActiveSheet"
        .Map "nmap <cmd>print PrintPreviewAndPrint"
        .Map "nmap <cmd>e OpenWorkbook"
        .Map "nmap <cmd>e! ReopenActiveWorkbook"
        .Map "nmap <cmd>w SaveWorkbook"
        .Map "nmap <cmd>q CloseAskSaving"
        .Map "nmap <cmd>q! CloseWithoutSaving"
        .Map "nmap <cmd>wq CloseWithSaving"
        .Map "nmap <cmd>x CloseWithSaving"
        .Map "nmap <cmd>saveas SaveAsNewWorkbook"
        .Map "nmap <cmd>b ActivateWorkbook"
        .Map "nmap <cmd>bnext NextWorkbook"
        .Map "nmap <cmd>bprevious PreviousWorkbook"
        .Map "nmap ZZ CloseWithSaving"
        .Map "nmap ZQ CloseWithoutSaving"
        .Map "nmap ]b NextWorkbook"
        .Map "nmap [b PreviousWorkbook"
        .Map "nmap u Undo_CtrlZ"
        .Map "nmap <C-z> Undo_CtrlZ"
        .Map "nmap <C-r> RedoExecute"
        .Map "nmap . RepeatAction"
        .Map "nmap m ZoomIn"
        .Map "nmap M ZoomOut"
        .Map "nmap % ZoomSpecifiedScale"
        .Map "nmap <bslash> ShowContextMenu"
        .Map "nmap <cmd>sort Sort 1"
        .Map "nmap <cmd>sort! Sort 2"
        .Map "nmap <cmd>opendir OpenActiveBookDir"
        .Map "nmap <cmd>fullpath YankActiveBookPath"
        .Map "nmap <C-i> JumpNext"
        .Map "nmap <C-o> JumpPrev"
        .Map "nmap <cmd>clearjumps ClearJumps"
        .Map "nmap <cmd>help SearchHelp"
        .Map "nmap gs ShowSummaryInfo"
        .Map "nmap zp SetPrintArea"
        .Map "nmap zP ClearPrintArea"
        .Map "nmap @@ ShowMacroDialog"
        '.Map "nmap 1 SubstituteType 1"
        '.Map "nmap 2 SubstituteType 2"
        '.Map "nmap 3 SubstituteType 3"
        '.Map "nmap 4 SubstituteType 4"
        '.Map "nmap 5 SubstituteType 5"
        '.Map "nmap 6 SubstituteType 6"
        '.Map "nmap 7 SubstituteType 7"
        '.Map "nmap 8 SubstituteType 8"
        '.Map "nmap 9 SubstituteType 9"
        .Map "cmap <Tab> ShowSuggest"
        .Map "cmap <C-w> <key><C-BS>"
        .Map "cmap <C-u> <key><S-Home><BS>"
        .Map "cmap <C-k> <key><S-End><Del>"
        .Map "cmap <C-h> <key><Left>"
        .Map "cmap <C-l> <key><Right>"
        .Map "cmap <C-a> <key><Home>"

    End With
End Sub

