using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Microsoft.Office.Interop.Word;

[Guid("9C1DBE08-4499-311E-B83E-27B844624F91")]
[CompilerGenerated]
[TypeIdentifier("00020905-0000-0000-c000-000000000046", "Microsoft.Office.Interop.Word.WdListNumberStyle")]
public enum WdListNumberStyle
{
	wdListNumberStyleArabic = 0,
	wdListNumberStyleUppercaseRoman = 1,
	wdListNumberStyleLowercaseRoman = 2,
	wdListNumberStyleUppercaseLetter = 3,
	wdListNumberStyleLowercaseLetter = 4,
	wdListNumberStyleOrdinal = 5,
	wdListNumberStyleCardinalText = 6,
	wdListNumberStyleOrdinalText = 7,
	wdListNumberStyleKanji = 10,
	wdListNumberStyleKanjiDigit = 11,
	wdListNumberStyleAiueoHalfWidth = 12,
	wdListNumberStyleIrohaHalfWidth = 13,
	wdListNumberStyleArabicFullWidth = 14,
	wdListNumberStyleKanjiTraditional = 16,
	wdListNumberStyleKanjiTraditional2 = 17,
	wdListNumberStyleNumberInCircle = 18,
	wdListNumberStyleAiueo = 20,
	wdListNumberStyleIroha = 21,
	wdListNumberStyleArabicLZ = 22,
	wdListNumberStyleBullet = 23,
	wdListNumberStyleGanada = 24,
	wdListNumberStyleChosung = 25,
	wdListNumberStyleGBNum1 = 26,
	wdListNumberStyleGBNum2 = 27,
	wdListNumberStyleGBNum3 = 28,
	wdListNumberStyleGBNum4 = 29,
	wdListNumberStyleZodiac1 = 30,
	wdListNumberStyleZodiac2 = 31,
	wdListNumberStyleZodiac3 = 32,
	wdListNumberStyleTradChinNum1 = 33,
	wdListNumberStyleTradChinNum2 = 34,
	wdListNumberStyleTradChinNum3 = 35,
	wdListNumberStyleTradChinNum4 = 36,
	wdListNumberStyleSimpChinNum1 = 37,
	wdListNumberStyleSimpChinNum2 = 38,
	wdListNumberStyleSimpChinNum3 = 39,
	wdListNumberStyleSimpChinNum4 = 40,
	wdListNumberStyleHanjaRead = 41,
	wdListNumberStyleHanjaReadDigit = 42,
	wdListNumberStyleHangul = 43,
	wdListNumberStyleHanja = 44,
	wdListNumberStyleHebrew1 = 45,
	wdListNumberStyleArabic1 = 46,
	wdListNumberStyleHebrew2 = 47,
	wdListNumberStyleArabic2 = 48,
	wdListNumberStyleHindiLetter1 = 49,
	wdListNumberStyleHindiLetter2 = 50,
	wdListNumberStyleHindiArabic = 51,
	wdListNumberStyleHindiCardinalText = 52,
	wdListNumberStyleThaiLetter = 53,
	wdListNumberStyleThaiArabic = 54,
	wdListNumberStyleThaiCardinalText = 55,
	wdListNumberStyleVietCardinalText = 56,
	wdListNumberStyleLowercaseRussian = 58,
	wdListNumberStyleUppercaseRussian = 59,
	wdListNumberStyleLowercaseGreek = 60,
	wdListNumberStyleUppercaseGreek = 61,
	wdListNumberStyleArabicLZ2 = 62,
	wdListNumberStyleArabicLZ3 = 63,
	wdListNumberStyleArabicLZ4 = 64,
	wdListNumberStyleLowercaseTurkish = 65,
	wdListNumberStyleUppercaseTurkish = 66,
	wdListNumberStyleLowercaseBulgarian = 67,
	wdListNumberStyleUppercaseBulgarian = 68,
	wdListNumberStylePictureBullet = 249,
	wdListNumberStyleLegal = 253,
	wdListNumberStyleLegalLZ = 254,
	wdListNumberStyleNone = 255
}
